School Management System/Areas/Admin/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School_Management_System.Areas.Models;
using SchoolManagementSystem.Domain.Abstract;
using SchoolManagementSystem.Domain.EditModels;
using SchoolManagementSystem.Domain.Entities;
using SchoolManagementSystem.Domain.ViewModels;

namespace School_Management_System.Areas.Admin.Controllers
{
    public class CoursesController : Controller
    {
        // GET: Admin/Courses
        private readonly ICoursesRepository repository;
        public int PageSize = 10;
        Courses Courses = new Courses();

        public CoursesController(ICoursesRepository coursesRepository)
        {
            this.repository = coursesRepository;
        }
        public ActionResult Index()
        {

            CoursesListViewModel model = new CoursesListViewModel();

            model.Courses = repository.GetAllCourses();

            return View(model);
           
        }
        [HttpPost]
        public JsonResult AddCourses(CoursesViewModel model)
        {
            Courses courses = new Courses();

            //courses.Id = model.Id;
            courses.Course_Name = model.Course_Name;
            courses.Course_Description = model.Course_Description;
            courses.School_Year = model.School_Year;

            repository.SaveCourses(courses);

            return Json(new
            {
                message = "Successfully added ",
                success = "true"
            });
        }

        [HttpPost]
        public JsonResult Deleted(int ID)
        {

            var courses = repository.GetCoursesById(ID);

            repository.DeleteCourses(courses);

            return Json(new
            {
                message = "Deleted Succesfully ",
                success = "true"
            });
        }
        //new edit
        [HttpPost]
        public JsonResult Edited(EditCoursesModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;
            if (model.Id > 0) // tyring to edit model
            {
                var courses = repository.GetCoursesById(model.Id);

                //courses.C = model.AccomodationPackageID;

                courses.Id = model.Id;
                courses.Course_Name = model.Course_Name;
                courses.Course_Description = model.Course_Description;
                courses.School_Year = model.School_Year;


                repository.UpdateCourses(courses);
            }
            else // create the record
            {
                Courses courses = new Courses();
                courses.Id = model.Id;
                courses.Course_Name = model.Course_Name;
                courses.Course_Description = model.Course_Description;
                courses.School_Year = model.School_Year;

                repository.SaveCourses(courses);

            }

            if (result)
            {

                json.Data = new { Success = true };
            }
            else
            {

                json.Data = new { Success = false, Message = "Unable to perform action on  Courses" };
            }

            return json;
        }
        ////new edited
        //[HttpPost]
        //public JsonResult Edited(EditCoursesModel model)
        //{
        //    var courses = repository.GetCoursesById(model.Id);

        //    courses.Id = model.Id;
        //    courses.Course_Name = model.Course_Name;
        //    courses.Course_Description = model.Course_Description;
        //    courses.School_Year = model.School_Year;

        //    repository.UpdateCourses(courses);

        //    return Json(new
        //    {
        //        message = "Updated Succesfully ",
        //        success = "true"
        //    });
        //}

        public ActionResult Details(int id)
        {
            var courses = repository.GetCoursesById(id);
            return View(courses);
        }



    
    }
}

School Management System/Areas/Admin/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School_Management_System.Areas.Models;
using SchoolManagementSystem.Domain.Abstract;
using SchoolManagementSystem.Domain.EditModels;
using SchoolManagementSystem.Domain.Entities;
using SchoolManagementSystem.Domain.ViewModels;

namespace School_Management_System.Areas.Admin.Controllers
{
    public class StaffController : Controller
    {
        // GET: Admin/Staff
        private readonly IStaffRepository repository;
        public int PageSize = 10;

        public StaffController(IStaffRepository staffRepository)
        {
            this.repository = staffRepository;
        }
        public ActionResult Index()
        {

            StaffListViewModel model = new StaffListViewModel();

            model.Staffs = repository.GetAllStaffs();

            return View(model);
        }

        [HttpPost]
        public JsonResult AddStaff(StaffViewModel model)
        {
            Staff staff = new Staff();

            staff.Id = model.Id;
            staff.Lastname = model.Lastname;
            staff.FirstName = model.FirstName;
            staff.Gender = model.Gender;
            staff.Age = model.Age;
            staff.Email = model.Email;
            staff.Address = model.Address;
            staff.Password = model.Password;


            repository.SaveStaff(staff);

            return Json(new
            {
                message = "Successfully added ",
                success = "true"
            });
        }

        [HttpPost]
        public JsonResult Deleted(int ID)
        {

            var staff = repository.GetStaffById(ID);

            repository.DeleteStaff(staff);

            return Json(new
            {
                message = "Deleted Succesfully ",
                success = "true"
            });
        }

        //new edited
        [HttpPost]
        public JsonResult Edited(EditStaffModel model)
        {
            var staff = repository.GetStaffById(model.Id);

            staff.Id = model.Id;
            staff.Lastname = model.Lastname;
            staff.FirstName = model.FirstName;
            staff.Gender = model.Gender;
            staff.Age = model.Age;
            staff.Email = model.Email;
            staff.Address = model.Address;
            staff.Password = model.Password;


            repository.UpdateStaff(staff);

            return Json(new
            {
                message = "Updated Succesfully ",
                success = "true"
            });
        }

        public ActionResult Details(int id)
        {
            var staff = repository.GetStaffById(id);
            return View(staff);
        }
    }
}

School Management System/Areas/Admin/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School_Management_System.Areas.Models;
using School_Management_System.Models;
using SchoolManagementSystem.Domain.Abstract;
using SchoolManagementSystem.Domain.EditModels;
using SchoolManagementSystem.Domain.Entities;
using SchoolManagementSystem.Domain.ViewModels;

namespace School_Management_System.Areas.Admin.Controllers
{
    public class StudentController : Controller
    {
        //public StudentController() { }
        private readonly IStudentRepository repository;
        public int PageSize = 30;

        public StudentController(IStudentRepository studentRepository)
        {
            this.repository = studentRepository;
        }
        public ActionResult Index(string firstname, int page = 1)
        {

            StudentListViewModels model = new StudentListViewModels
            {
                Students = repository.GetAllStudents()
                .Where(p => firstname == null || p.FirstName == firstname)
               //.Where(p => category == null || p.Category == category)
               .OrderBy(p => p.Id)
               .Skip((page - 1) * PageSize)
               .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = firstname == null ?
                   repository.GetAllStudents().Count() :
                   repository.GetAllStudents().Where(e => e.FirstName == firstname /* Category == category*/).Count()
                },
            };
            return View(model);

        }
        [HttpPost]
        public JsonResult AddStudent(StudentViewModel model)
        {

            Student student = new Student
            {
                LastName = model.LastName,
                FirstName = model.FirstName,
                Gender = model.Gender,
                Age = model.Age,
                Address = model.Address,
                Phone = model.Phone,
                Email = model.Email,
                Password = model.Password
            };


            repository.SaveStudent(student);

            return Json(new
            {
                message = "Successfully added ",
                success = "true"
            });
        }

        [HttpPost]
        public JsonResult Deleted(int id)
        {

            var student = repository.GetStudentById(id);

            repository.DeleteStudent(student);

            return Json(new
            {
                message = "Deleted Succesfully ",
                success = "true"
            });
        }

        //new edited
        [HttpPost]
        public JsonResult Edited(EditStudentModels model)
        {
            var student = repository.GetStudentById(model.Id);

            student.LastName = model.LastName;
            student.FirstName = model.FirstName;
            student.Gender = model.Gender;
            student.Age = model.Age;
            student.Address = model.Address;
            student.Phone = model.Phone;
            student.Email = model.Email;
            student.Password = model.Password;


            repository.UpdateStudent(student);

            return Json(new
            {
                message = "Updated Succesfully ",
                success = "true"
            });

        }
    }
}

School Management System/Areas/Admin/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School_Management_System.Areas.Models;
using SchoolManagementSystem.Domain.Abstract;
using SchoolManagementSystem.Domain.EditModels;
using SchoolManagementSystem.Domain.Entities;
using SchoolManagementSystem.Domain.ViewModels;

namespace School_Management_System.Areas.Admin.Controllers
{
    public class SubjectsController : Controller
    {
        // GET: Admin/Subjects
        private readonly ISubjectsRepository repository;
        public int PageSize = 10;

        public SubjectsController(ISubjectsRepository subjectsRepository)
        {
            this.repository = subjectsRepository;
        }
        public ActionResult Index()
        {
            SubjectsListViewModel model = new SubjectsListViewModel();

            model.Subjects = repository.GetAllSubjects();

            return View(model);
            
        }
        [HttpPost]
        public JsonResult AddSubjects(SubjectsViewModel model)
        {
            Subjects subjects = new Subjects();

            subjects.Id = model.Id;
            subjects.Name = model.Name;
            subjects.Course_Id = model.Course_Id;


            repository.SaveSubjects(subjects);

            return Json(new
            {
                message = "Successfully added ",
                success = "true"
            });
        }
        [HttpPost]
        public JsonResult Deleted(int ID)
        {

            var subjects = repository.GetSubjectsById(ID);

            repository.DeleteSubjects(subjects);

            return Json(new
            {
                message = "Deleted Succesfully ",
                success = "true"
            });
        }

        //new edited
        [HttpPost]
        public JsonResult Edited(EditSubjectsModel model)
        {
            var subjects = repository.GetSubjectsById(model.Id);

            subjects.Id = model.Id;
            subjects.Name = model.Name;
            subjects.Course_Id = model.Course_Id;

            repository.UpdateSubjects(subjects);

            return Json(new
            {
                message = "Updated Succesfully ",
                success = "true"
            });
        }

        public ActionResult Details(int id)
        {
            var subjects = repository.GetSubjectsById(id);
            return View(subjects);
        }
    }
}

School Management System/Areas/Admin/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - School Management System</title>

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    @*///css new*@
    <link href="~/Areas/Admin/Content/css/styles.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/Vendor/bootstrap/bootstrap.min.css" rel="stylesheet" />
    @*//css new*@
    <link href="~/Areas/Dashboard/Content/Vendor/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Dashboard/Content/css/styles.css" rel="stylesheet" />

    <script src="https://kit.fontawesome.com/adf95bd522.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Dashboard/Content/Vendor/jquery/jquery-1.10.2.min.js"></script>

</head>
<body>
    <div class="d-flex" id="wrapper">
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <i class="fa fa-globe" aria-hidden="true"></i> School Management System
            </div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index", "Student")" class="list-group-item list-group-item-action bg-light">
                    <i @*class="fa fa-cutlery"*@ aria-hidden="true"></i> Students
                </a>
                <a href="@Url.Action("Index", "Staff")" class="list-group-item list-group-item-action bg-light">
                    <i @*class="fa fa-cutlery"*@ aria-hidden="true"></i> Staffs
                </a>
                <a href="@Url.Action("Index", "Schedules")" class="list-group-item list-group-item-action bg-light">
                    <i @*class="fa fa-cutlery"*@ aria-hidden="true"></i> Schedules
                </a>
                <a href="@Url.Action("Index", "Courses")" class="list-group-item list-group-item-action bg-light">
                    <i @*class="fa fa-cutlery"*@ aria-hidden="true"></i> Courses
                </a>
                <a href="@Url.Action("Index", "Subjects")" class="list-group-item list-group-item-action bg-light">
                    <i @*class="fa fa-cutlery"*@ aria-hidden="true"></i> Subjects
                </a>
                <a href="@Url.Action("Index", "Transactions")" class="list-group-item list-group-item-action bg-light">
                    <i @*class="fa fa-cutlery"*@ aria-hidden="true"></i> Transactions
                </a>

            </div>
        </div>

        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">
                    <i class="fas fa-bars"></i>
                </button>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home")">
                                <i class="fa-solid fa-house-chimney"></i>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">
                                <i class="fa-solid fa-right-from-bracket mr-1"></i>Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            @*Page content
        <div class="container-fluid">
            @RenderBody()
        </div>*@

            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
    }

    @*/wrapper
    <script src="~/Areas/Admin/Content/vendor/js/bootstrap.bundle.min.js"></script>
    Menu Toggle Script
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>*@
    <!-- /wrapper -->
    @*<script src="~/Areas/Admin/Content/vendor/js/bootstrap.bundle.min.js"></script>*@


    <script src="~/Areas/Admin/Content/Vendor/js/bootstrap.bundle.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
</body>
        </html>